apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres14
  labels:
    app: postgres14
spec:
  serviceName: postgres14
  replicas: 1
  selector:
    matchLabels:
      app: postgres14
  template:
    metadata:
      labels:
        app: postgres14
    spec:
      containers:
      - name: postgres
        image: postgres:14
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: true
        envFrom:
        - configMapRef:
            name: postgres14-config
        - secretRef:
            name: postgres14-secrets
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: run
          mountPath: /var/run
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres", "-h", "localhost"]
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres", "-h", "localhost"]
      volumes:
      - name: run
        emptyDir: {}

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
